CUDA_VISIBLE_DEVICES=1,2 python graphlens/entropy.py \
  --model_path /home/lym/data1/LLM-model/meta-llama/Meta-Llama-3.1-8B-Instruct \
  --task_name GraphWiz \
  --data_dir /home/lym/data1/Datasets/GraphWiz/GraphInstruct-Test \
  --output_dir ../outputs/entropy_results \
  --input_column input_prompt \
  --sample_num 50 \
  --min_edges 70 \
  --max_edges 130 \
  --score_mode per_layer \
  --alpha 1.0